# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3f476c562b8bff2f05dfb826c0f5d92a10519ff92b0cbe401406f7c3a5f24ed076cf746564eb5e3f252ccbd255ba0522c73b7386ecfd99cde45d7457e2cb564e

test:
  secret_key_base: 23c0a6baaa0211a622a532a9cedcee10e3762ccb39afd1f98632b48fc96110977c6762b6d9850b8bb5ddbf43085c70d11b30f7ba213691fb0092a02d11d3a4cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
